### ISSUE TITLE
Nightly upgrade misses upgrade.properties file

### ISSUE THREAD

**Issue by sdimitro** [delphix/appliance-build#461]
Link: http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/dcol-nightly-upgrade-dc1/1/execution/node/25/log/

```
13:02:46  + sudo /var/dlpx-update/latest/upgrade -v deferred
13:02:46  /var/dlpx-update/latest/common.sh: line 293: /var/dlpx-update/upgrade.properties: No such file or directory
```

**Comment by prakashsurya** [comment]
That error is expected, given that the file should not exist at the time it was run.. i.e.
```
06:02:46  + sudo /var/dlpx-update/latest/upgrade -v deferred
06:02:46  /var/dlpx-update/latest/common.sh: line 293: /var/dlpx-update/upgrade.properties: No such file or directory
06:02:46  upgrade: upgrade currently in-progress
```

The "issue" is that we're detecting an upgrade is in-progress, when that's not true.

We have this function:
```
292 function verify_upgrade_not_in_progress() {                                     
293 >       . "$UPDATE_DIR/upgrade.properties"                                      
294                                                                                 
295 >       [[ -z "$UPGRADE_TYPE" ]] || die "upgrade currently in-progress"         
296 }  
```
the idea being, we read in `upgrade.properties`, and expect that `source` call to set the `UPGRADE_TYPE` variable if an upgrade is in-progress.

If an upgrade is not in-progress, the file may not exist (and hence that "error" is "expected").. or it will not contain the `UPGRADE_TYPE` field (e.g. the file is empty). In both cases, the `UPGRADE_TYPE` variable will not be set after the call to `source`.

The problem is we call this function in the `upgrade` script, after we set the `UPGRADE_TYPE` variable.. e.g.
```
478 >       UPGRADE_TYPE="FULL"                                                     
479 >       shift 1                                                                 
480 >       verify_upgrade_is_allowed                                               
481 >       verify_upgrade_not_in_progress  
```
So, even when there isn't an in-progress upgrade, we'll have already set the `UPGRADE_TYPE` variable, causing the `verify_upgrade_not_in_progress` function to misbehave.
